services:
  - type: web
    name: caca-palavras
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PORT
        value: 8080
